# Generated by the bump workflow in this repository from what releases.knaix.com
# serves. Edit scripts/render-formula.sh, not this file.
class Knaix < Formula
  desc "Command-line client for Kovalent: private AI nodes with cited answers"
  homepage "https://knaix.com"
  version "0.6.2"
  license "Apache-2.0"

  # No livecheck block. It cannot pass brew style here: with no top-level url,
  # the LivecheckUrlSymbol cop reads livecheck's own url as the stable one and
  # demands `url :stable`, while ComponentsOrder demands livecheck sit above the
  # on_macos block where that happens. CI compares this version against
  # releases.knaix.com/latest-version instead, which fails louder anyway.

  on_macos do
    on_arm do
      url "https://releases.knaix.com/v0.6.2/knaix-darwin-arm64"
      sha256 "6d93aa0e1f63ad0261f14d796146fce5c542a79896c9b1e59a903c72e5c1f2ab"
    end
    on_intel do
      url "https://releases.knaix.com/v0.6.2/knaix-darwin-x86_64"
      sha256 "a3f5befeb8612e1d2ed7e71185832f9f574507a732660567d3d9686ca95c021a"
    end
  end

  on_linux do
    on_arm do
      url "https://releases.knaix.com/v0.6.2/knaix-linux-arm64"
      sha256 "9339c12f17671455cae0e358c0aa4a18575b44ec4d173781ddc4533aaedd44ac"
    end
    on_intel do
      url "https://releases.knaix.com/v0.6.2/knaix-linux-x86_64"
      sha256 "6c11d8196b87ec25ef46b0138a6172cac9805ec70264368dc6685d0346f5e219"
    end
  end

  def install
    # The published artifacts are bare binaries rather than archives, so the
    # staged file is renamed onto PATH instead of extracted. It arrives 0644
    # from the bucket and install keeps that mode, so set it before anything
    # tries to run the binary.
    bin.install Dir["knaix-*"].first => "knaix"
    chmod 0755, bin/"knaix"
    generate_completions_from_executable(bin/"knaix", "completions")
  end

  def caveats
    <<~EOS
      Start a node on this machine:
        knaix local setup

      Or sign in to a node Kovalent runs for you:
        knaix login
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/knaix --version")
    assert_match "_knaix", shell_output("#{bin}/knaix completions bash")
  end
end
