# Generated by knaix-cli's tap-bump workflow. Edit that template, not this file.
class Knaix < Formula
  desc "Command-line client for Kovalent: private AI nodes with cited answers"
  homepage "https://knaix.com"
  version "0.4.8"
  license "Apache-2.0"

  # No livecheck block. It cannot pass brew style here: with no top-level url,
  # the LivecheckUrlSymbol cop reads livecheck's own url as the stable one and
  # demands `url :stable`, while ComponentsOrder demands livecheck sit above the
  # on_macos block where that happens. CI compares this version against
  # releases.knaix.com/latest-version instead, which fails louder anyway.

  on_macos do
    on_arm do
      url "https://releases.knaix.com/v0.4.8/knaix-darwin-arm64"
      sha256 "3c54a5564c7bde94400524adadeb2cca69f79f632b12f18fc4552ba2a52d57c4"
    end
    on_intel do
      url "https://releases.knaix.com/v0.4.8/knaix-darwin-x86_64"
      sha256 "ac648d9af1491a94834160f2f95a5dbaba99290cf0b44c3792d0dc85c9fa79f4"
    end
  end

  on_linux do
    on_arm do
      url "https://releases.knaix.com/v0.4.8/knaix-linux-arm64"
      sha256 "1f08c1c784f9ae7e67a24dd7028a6eba5f75258466a7ef1cec6f969149bf8d69"
    end
    on_intel do
      url "https://releases.knaix.com/v0.4.8/knaix-linux-x86_64"
      sha256 "81419ce135a470518816d371deb02b670b7791de4041880ef89d6e804c3db390"
    end
  end

  def install
    # The published artifacts are bare binaries rather than archives, so the
    # staged file is renamed onto PATH instead of extracted. It arrives 0644
    # from the bucket and install keeps that mode, so set it before anything
    # tries to run the binary.
    bin.install Dir["knaix-*"].first => "knaix"
    chmod 0755, bin/"knaix"
    generate_completions_from_executable(bin/"knaix", "completions")
  end

  def caveats
    <<~EOS
      Start a node on this machine:
        knaix local setup

      Or sign in to a node Kovalent runs for you:
        knaix login
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/knaix --version")
    assert_match "_knaix", shell_output("#{bin}/knaix completions bash")
  end
end
