# Generated by the bump workflow in this repository from what releases.knaix.com
# serves. Edit scripts/render-formula.sh, not this file.
class Knaix < Formula
  desc "Command-line client for Kovalent: private AI nodes with cited answers"
  homepage "https://knaix.com"
  version "0.6.1"
  license "Apache-2.0"

  # No livecheck block. It cannot pass brew style here: with no top-level url,
  # the LivecheckUrlSymbol cop reads livecheck's own url as the stable one and
  # demands `url :stable`, while ComponentsOrder demands livecheck sit above the
  # on_macos block where that happens. CI compares this version against
  # releases.knaix.com/latest-version instead, which fails louder anyway.

  on_macos do
    on_arm do
      url "https://releases.knaix.com/v0.6.1/knaix-darwin-arm64"
      sha256 "cffb8c5371615a2868b4f0945fee430b686ca53991459317beac90f97fdf483e"
    end
    on_intel do
      url "https://releases.knaix.com/v0.6.1/knaix-darwin-x86_64"
      sha256 "b778b9735e2da42e638272d2a7ec5462487dae635b9743e6b5dbd9e36fb66d4a"
    end
  end

  on_linux do
    on_arm do
      url "https://releases.knaix.com/v0.6.1/knaix-linux-arm64"
      sha256 "19d1860bbf093affc04f0a27a4467a439a9ef89b42c9f5656a5571bdf9453dce"
    end
    on_intel do
      url "https://releases.knaix.com/v0.6.1/knaix-linux-x86_64"
      sha256 "0801803d8ceca230bbc946ade9359baf922734327d5a3ed154c9dfecdfad0893"
    end
  end

  def install
    # The published artifacts are bare binaries rather than archives, so the
    # staged file is renamed onto PATH instead of extracted. It arrives 0644
    # from the bucket and install keeps that mode, so set it before anything
    # tries to run the binary.
    bin.install Dir["knaix-*"].first => "knaix"
    chmod 0755, bin/"knaix"
    generate_completions_from_executable(bin/"knaix", "completions")
  end

  def caveats
    <<~EOS
      Start a node on this machine:
        knaix local setup

      Or sign in to a node Kovalent runs for you:
        knaix login
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/knaix --version")
    assert_match "_knaix", shell_output("#{bin}/knaix completions bash")
  end
end
